### ISSUE TITLE
Frontend cannot handle 404 on swagger subroute when swagger disabled

### ISSUE THREAD

**Issue by uvulpos** [uvulpos/golang-sveltekit-binary#46]
**Description**:
When I have swagger disabled and run `make dev` locally, I get cannot fetch js errors. Need to fix that.

**Steps to reproduce**
- Disable swagger in modd.conf
- Execute `make dev`
- Visit: http://web.localhost/swagger/index.html

**Expected Behaviour**
- SvelteKit Error Page

**Actual Behaviour**
```
web-ui                                   | Error: Not found: /_app/immutable/entry/start.6f1b4a92.js
web-ui                                   |     at resolve (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:483:13)
web-ui                                   |     at resolve (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
web-ui                                   |     at #options.hooks.handle (/app/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
web-ui                                   |     at Module.respond (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40)
web-ui                                   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web-ui                                   | Error: Not found: /_app/immutable/chunks/scheduler.571a1093.js
web-ui                                   |     at resolve (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:483:13)
web-ui                                   |     at resolve (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
web-ui                                   |     at #options.hooks.handle (/app/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
web-ui                                   |     at Module.respond (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40)
web-ui                                   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web-ui                                   | Error: Not found: /_app/immutable/chunks/index.54d92eec.js
web-ui                                   |     at resolve (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:483:13)
web-ui                                   |     at resolve (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
web-ui                                   |     at #options.hooks.handle (/app/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
web-ui                                   |     at Module.respond (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40)
web-ui                                   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web-ui                                   | Error: Not found: /_app/immutable/chunks/index.bcd33156.js
web-ui                                   |     at resolve (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:483:13)
web-ui                                   |     at resolve (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
web-ui                                   |     at #options.hooks.handle (/app/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
web-ui                                   |     at Module.respond (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40)
web-ui                                   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web-ui                                   | Error: Not found: /_app/immutable/entry/app.e0ab6711.js
web-ui                                   |     at resolve (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:483:13)
web-ui                                   |     at resolve (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
web-ui                                   |     at #options.hooks.handle (/app/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
web-ui                                   |     at Module.respond (/app/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40)
web-ui                                   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Additional Information:**

**Comment by uvulpos** [comment]
not critical! Binary handles 404 just fine. Added another 404 handler already in other commit to prevent 500 on not /api routes
